- contrib/forms/cotutelle.py
- locale/fr_BE/LC_MESSAGES/django.po
- tests/views/test_cotutelle.py
see https://jira.sgsi.ucl.ac.be/browse/OS-96
> OS-96 Cotutelle fixes

- requirements.txt
- templates/admission/doctorate/admission_doctorate_list.html
- templates/admission/doctorate/detail_tab_layout.html
- https://github.com/uclouvain/osis-admission/pull/35 must be merged before.
- A new sdk must be generated and then used in this PR.
> OS-86 : Use the admission reference field

- contrib/enums/proximity_commission.py
- contrib/forms/project.py
- contrib/views/detail_tabs/project.py
- contrib/views/form_tabs/project.py
- locale/fr_BE/LC_MESSAGES/django.po
- services/proposition.py
- templates/admission/doctorate/detail_project.html
- templates/admission/doctorate/form_tab_project.html
- tests/views/test_project.py
see https://jira.sgsi.ucl.ac.be/browse/OS-101
> OS-101 Transform Bureau field to Proximity commission

- contrib/views/detail_tabs/coordonnees.py
- contrib/views/detail_tabs/education.py
- contrib/views/detail_tabs/person.py
- contrib/views/form_tabs/coordonnees.py
- contrib/views/form_tabs/education.py
- contrib/views/form_tabs/person.py
- contrib/views/form_tabs/project.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- services/mixins.py
- services/person.py
- templates/admission/doctorate/detail_tab_layout.html
- templates/admission/doctorate/form_tab_layout.html
- tests/views/test_project.py
> Use uuid for person-related tab

- contrib/enums/projet.py
- contrib/forms/supervision.py
- contrib/views/detail_tabs/person.py
- contrib/views/detail_tabs/supervision.py
- contrib/views/form_tabs/supervision.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- services/person.py
- services/proposition.py
- templates/admission/doctorate/admission_doctorate_list.html
- templates/admission/doctorate/cancel.html
- templates/admission/doctorate/detail_tab_layout.html
- templates/admission/doctorate/form_tab_layout.html
- templates/admission/doctorate/form_tab_project.html
- templates/admission/doctorate/form_tab_supervision.html
- templates/panel.html
- templatetags/admission.py
- tests/test_templatetags.py
- tests/views/test_person.py
- tests/views/test_project.py
- tests/views/test_supervision.py
> Better admission list display

- contrib/forms/supervision.py
- contrib/views/__init__.py
- contrib/views/detail_tabs/supervision.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- services/proposition.py
- templates/admission/doctorate/form_tab_supervision.html
- templates/admission/doctorate/includes/supervision_member_entry.html
- tests/views/test_supervision.py
- urls.py
- Needs https://github.com/uclouvain/osis-admission/pull/86
> OS-57 Approval by pdf

- contrib/enums/proximity_commission.py
- contrib/forms/project.py
- contrib/views/autocomplete.py
- contrib/views/form_tabs/project.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- templates/admission/doctorate/detail_project.html
- templates/admission/doctorate/form_tab_project.html
- tests/views/test_autocomplete.py
- tests/views/test_project.py
- needs https://github.com/uclouvain/osis-admission/pull/92
> OS-131 Subdomain for science doctorate

- contrib/views/form_tabs/coordonnees.py
- tests/views/test_coordonnees.py
> Prevent to post an empty contact address if it is not desired

- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- templates/admission/doctorate/includes/supervision_member_entry.html
Related 
- https://github.com/uclouvain/osis-admission/pull/108
> OS-115 Switch from modal to collapsible form for pdf approval

- contrib/forms/project.py
- contrib/views/autocomplete.py
- contrib/views/detail_tabs/project.py
- contrib/views/form_tabs/project.py
- requirements.txt
- templates/admission/doctorate/admission_doctorate_list.html
- templates/admission/doctorate/cancel.html
- templates/admission/doctorate/detail_project.html
- templates/admission/doctorate/detail_tab_layout.html
- templates/admission/doctorate/form_tab_layout.html
- templates/admission/doctorate/form_tab_project.html
- templates/admission/doctorate/form_tab_supervision.html
- templates/admission/doctorate/supervised_list.html
- tests/views/test_autocomplete.py
- tests/views/test_project.py
> Directly use the translated doctorate and sector names

- requirements.txt
- services/proposition.py
- templates/admission/doctorate/admission_doctorate_list.html
- templates/admission/doctorate/supervised_list.html
- templates/admission/doctorate_tab_entry.html
- templates/admission/doctorate_tabs_bar.html
- templatetags/admission.py
- tests/views/test_list.py
> OS-139 Display tab status in tab bar

- constants.py
- contrib/forms/extension_request.py
- contrib/views/__init__.py
- contrib/views/detail_tabs/extension_request.py
- contrib/views/form_tabs/extension_request.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- services/proposition.py
- templates/admission/doctorate/detail_extension_request.html
- templates/admission/doctorate/form_tab_extension_request.html
- templates/admission/doctorate/includes/new_deadline_description.html
- templatetags/admission.py
- tests/forms/test_extension_request.py
- tests/views/test_extension_request.py
- urls.py
> OS-153: Add the pages related to the deadline extension request of a confirmation paper

- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- templates/admission/doctorate/form_tab_supervision.html
- tests/views/test_supervision.py
Needs 
- https://github.com/uclouvain/osis-admission/pull/156
> OS-26 Display pdf link

- contrib/enums/person.py
- contrib/forms/person.py
- contrib/views/form_tabs/coordonnees.py
- contrib/views/form_tabs/person.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- services/person.py
- templates/admission/doctorate/details/person.html
- templates/admission/doctorate/forms/person.html
- tests/views/test_person.py
> [OS-250] Modifications of the choice of the proof of identity

- contrib/enums/curriculum.py
- contrib/forms/__init__.py
- contrib/forms/curriculum.py
- contrib/views/autocomplete.py
- contrib/views/detail_tabs/curriculum.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- services/reference.py
- templates/admission/doctorate/details/curriculum_educational_experience.html
- templates/admission/doctorate/forms/curriculum_educational_experience.html
- templates/admission/doctorate/includes/curriculum_experience_list.html
- tests/views/curriculum/mixin.py
- tests/views/curriculum/test_academic_experience.py
- urls.py
> [OS-196-institute] Add the institute field based on organization model

- constants.py
- contrib/enums/__init__.py
- contrib/enums/accounting.py
- contrib/forms/accounting.py
- contrib/views/__init__.py
- contrib/views/detail_tabs/accounting.py
- contrib/views/form_tabs/accounting.py
- contrib/views/form_tabs/confirm.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- services/proposition.py
- static/admission/admission.js
- templates/admission/doctorate/details/accounting.html
- templates/admission/doctorate/form_tab_layout.html
- templates/admission/doctorate/forms/accounting.html
- templates/admission/doctorate/forms/coordonnees.html
- templates/admission/doctorate/forms/doctorate_tab_layout.html
- templates/admission/doctorate/forms/person.html
- templatetags/admission.py
- tests/factories.py
- tests/views/curriculum/mixin.py
- tests/views/test_accounting.py
- urls.py
> [OS-252] Add the accounting tab

- contrib/forms/training.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- templates/admission/doctorate/details/training/ucl_course.html
- templates/admission/doctorate/forms/training.html
- templates/admission/doctorate/forms/training/activity_confirm_delete.html
- templates/admission/doctorate/forms/training/assent.html
- templatetags/admission.py
- tests/test_templatetags.py
Pull request automatique de hotfix/OS-312 vers DEV
> OS-312 Formation Doctorat - retours suite tests Makina

- contrib/forms/pool_questions.py
- contrib/views/common/confirm_submit.py
- contrib/views/common/detail_tabs/specific_questions.py
- contrib/views/common/form_tabs/specific_questions.py
- contrib/views/mixins.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- services/proposition.py
- templates/admission/details/specific_question.html
- templates/admission/forms/specific_question.html
- tests/views/test_specific_question.py
Needs 
- https://github.com/uclouvain/osis-admission/pull/292
> OS-379 Pool questions

- contrib/enums/financement.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- tests/views/test_project.py
> [OS-378] Update the working contract type

- contrib/forms/curriculum.py
- contrib/views/common/detail_tabs/curriculum.py
- contrib/views/common/detail_tabs/curriculum_experiences.py
- contrib/views/common/form_tabs/curriculum_experiences.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- static/admission/admission.css
- templates/admission/details/curriculum.html
- templates/admission/forms/curriculum_educational_experience.html
- templates/admission/forms/curriculum_experience_delete.html
- tests/views/curriculum/mixin.py
- tests/views/curriculum/test_academic_experience.py
- tests/views/curriculum/test_non_academic_experience.py
> [OS-402] Allow to update valuated academic experiences for a doctorate admission

- contrib/forms/education.py
- contrib/views/common/form_tabs/education.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- templates/admission/details/curriculum.html
- templates/admission/forms/education.html
- templates/admission/general_education/forms/bachelor_education.html
- templates/admission/includes/curriculum_experience_header.html
- templates/admission/tab_layout.html
- templatetags/admission.py
- tests/views/curriculum/test_academic_experience.py
- tests/views/curriculum/test_global.py
- tests/views/curriculum/test_non_academic_experience.py
- tests/views/test_education.py
- tests/views/test_languages.py
> [OS-401] Prevent to update the secondary studies if an admission already valuated them

- contrib/views/list.py
- requirements.txt
- services/proposition.py
- templates/admission/admission_list.html
- tests/utils/test_utils.py
- tests/views/test_list.py
- tests/views/test_training_choice/__init__.py
- tests/views/test_training_choice/test_create_training_choice.py
> [OS-383] Limit the number of created and submitted propositions

- contrib/enums/specific_question.py
- contrib/forms/specific_question.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- static/admission/admission.css
- templates/admission/tags/multiple_field_data.html
- templatetags/admission.py
- tests/forms/test_specific_question.py
- tests/test_templatetags.py
- tests/views/test_training_choice/__init__.py
> [OS-265] Add the selection form item

- contrib/enums/additional_information.py
- contrib/forms/additional_information.py
- contrib/forms/coordonnees.py
- contrib/views/common/form_tabs/specific_questions.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- services/proposition.py
- templates/admission/details/specific_question.html
- templates/admission/forms/specific_question.html
- tests/views/test_specific_question.py
- tests/views/test_training_choice/__init__.py
> [OS-406] Add the specific questions related to continuing education admissions

- contrib/enums/training_choice.py
- contrib/forms/curriculum.py
- contrib/forms/specific_question.py
- contrib/views/common/detail_tabs/curriculum_experiences.py
- contrib/views/common/form_tabs/confirm_submit.py
- contrib/views/common/form_tabs/curriculum_experiences.py
- requirements.txt
- services/proposition.py
- static/admission/admission.css
- templates/admission/forms/confirm-submit.html
- templates/admission/forms/curriculum_educational_experience.html
- templates/admission/forms/curriculum_experience_delete.html
- templates/admission/forms/curriculum_professional_experience.html
- templates/admission/forms/specific_question.html
- templates/admission/includes/curriculum_experience_year_form.html
- tests/forms/test_specific_question.py
- tests/views/curriculum/test_academic_experience.py
- tests/views/curriculum/test_non_academic_experience.py
- tests/views/test_confirm_submit.py
- tests/views/test_specific_question.py
- tests/views/test_training_choice/test_update_training_choice.py
> [OS-264] CV specificities and fixes

- contrib/forms/coordonnees.py
- contrib/forms/curriculum.py
- contrib/forms/person.py
- contrib/views/common/detail_tabs/coordonnees.py
- contrib/views/common/detail_tabs/curriculum.py
- contrib/views/common/detail_tabs/curriculum_experiences.py
- contrib/views/common/detail_tabs/education.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- static/admission/admission.css
- templates/admission/details/coordonnees.html
- templates/admission/details/curriculum.html
- templates/admission/details/curriculum_educational_experience.html
- templates/admission/details/curriculum_professional_experience.html
- templates/admission/details/education.html
- templates/admission/details/person.html
- templates/admission/details/specific_question.html
- templates/admission/forms/curriculum_educational_experience.html
- templates/admission/forms/curriculum_professional_experience.html
- templates/admission/forms/languages.html
- templates/admission/forms/person.html
- tests/views/curriculum/mixin.py
- tests/views/curriculum/test_non_academic_experience.py
- tests/views/test_education.py
- tests/views/test_person.py
- utils/__init__.py
- utils/utils.py
> Fixes and evolutions after tests

- contrib/forms/curriculum.py
- contrib/views/common/detail_tabs/curriculum.py
- contrib/views/common/form_tabs/curriculum.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- services/proposition.py
- templates/admission/general_education/details/curriculum.html
- templates/admission/general_education/forms/curriculum.html
- tests/views/curriculum/mixin.py
- tests/views/curriculum/test_global.py
> [OS-440] Remove the bachelor cycle continuation

- contrib/forms/supervision.py
- contrib/views/doctorate/supervision.py
- requirements.txt
- services/proposition.py
- templates/admission/doctorate/includes/supervision_member_entry.html
- templatetags/admission.py
- tests/views/test_supervision.py
- Needs https://github.com/uclouvain/osis-admission/pull/381
> OS-456 Edit external member

- contrib/enums/secondary_studies.py
- contrib/forms/additional_information.py
- contrib/forms/coordonnees.py
- contrib/forms/person.py
- contrib/forms/pool_questions.py
- contrib/views/common/detail_tabs/education.py
- contrib/views/common/form_tabs/confirm_submit.py
- contrib/views/common/form_tabs/coordonnees.py
- contrib/views/doctorate/project.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- static/admission/admission.js
- static/admission/formatter.js
- templates/admission/details/coordonnees.html
- templates/admission/details/curriculum_educational_experience.html
- templates/admission/details/education.html
- templates/admission/details/person.html
- templates/admission/details/specific_question.html
- templates/admission/doctorate/details/project.html
- templates/admission/doctorate/details/training_choice.html
- tests/views/curriculum/mixin.py
- tests/views/test_coordonnees.py
- tests/views/test_education.py
- tests/views/test_project.py
> [OS-419][OS-438] Harmonization with backoffice (tabs & pdf) 

- constants.py
- contrib/enums/projet.py
- contrib/enums/specific_question.py
- contrib/forms/documents.py
- contrib/forms/specific_question.py
- contrib/views/common/form_tabs/documents.py
- contrib/views/list.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- services/proposition.py
- templates/admission/forms/confirm_documents.html
- templates/admission/forms/documents.html
- templates/admission/includes/admission_list_item.html
- templates/admission/widgets/multiwidget.html
- templatetags/admission.py
- tests/views/test_documents.py
> [OS-431] Allow a candidate to upload the requested documents

- contrib/enums/secondary_studies.py
- contrib/forms/education.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- templates/admission/details/education.html
- templates/admission/general_education/forms/bachelor_education.html
- tests/views/test_education.py
> [OS-619] Remove the high school diploma result question

- constants.py
- contrib/enums/payment.py
- contrib/views/common/detail_tabs/payment.py
- contrib/views/common/form_tabs/confirm_submit.py
- contrib/views/doctorate/project.py
- contrib/views/list.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- services/proposition.py
- templates/admission/admission_list.html
- templates/admission/details/payment.html
- tests/views/test_payment.py
> [OS-610] Integrate the payment system

- contrib/forms/__init__.py
- contrib/forms/additional_information.py
- contrib/forms/coordonnees.py
- contrib/forms/curriculum.py
- contrib/forms/education.py
- contrib/forms/jury/membre.py
- contrib/forms/person.py
- contrib/forms/supervision.py
- contrib/forms/training.py
- contrib/views/autocomplete.py
- contrib/views/common/detail_tabs/specific_questions.py
- contrib/views/common/form_tabs/specific_questions.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- services/autocomplete.py
- services/diplomatic_post.py
- services/proposition.py
- static/admission/admission.css
- templates/admission/details/specific_question.html
- templates/admission/forms/specific_question.html
- templates/admission/general_education/forms/bachelor_education.html
- templatetags/admission.py
- tests/views/curriculum/mixin.py
- tests/views/test_autocomplete.py
- tests/views/test_specific_question.py
- tests/views/training_choice/__init__.py
> [OS-617] Add visa question

- contrib/views/common/form_tabs/specific_questions.py
- requirements.txt
- services/proposition.py
- templates/admission/details/specific_question.html
- templates/admission/forms/confirm-submit.html
- templates/admission/forms/specific_question.html
- tests/views/test_specific_question.py
> [OS-641] Display a warning message to prevent the enrolment for a limited course for the non-resident candidates

- contrib/enums/document.py
- contrib/forms/specific_question.py
- contrib/views/common/form_tabs/documents.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- services/proposition.py
- templates/admission/forms/documents.html
- tests/forms/test_specific_question.py
- tests/views/test_documents.py
> [OS-632] In the documents tab, separate the documents that are requested immediately from the others

- contrib/enums/document.py
- contrib/forms/specific_question.py
- contrib/views/common/form_tabs/documents.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- services/proposition.py
- templates/admission/forms/documents.html
- tests/forms/test_specific_question.py
- tests/views/test_documents.py
…ted immediately from the others
> [TEST] Release

- .gitignore
- README.md
- admin.py
- apps.py
- models.py
- tests.py
- urls.py
- views.py
Pull request automatique de hotfix/OS-650 vers DEV
> [WIP] [hotfix/OS-650 => DEV] Front-office : Le tri et la recherche lors de la sélection du pays n_est pas fonctionnel en langue EN

- contrib/forms/accounting.py
- contrib/forms/additional_information.py
- contrib/forms/coordonnees.py
- contrib/forms/cotutelle.py
- contrib/forms/curriculum.py
- contrib/forms/education.py
- contrib/forms/person.py
- contrib/forms/project.py
- contrib/forms/supervision.py
- contrib/views/autocomplete.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- services/mixins.py
- tests/views/test_autocomplete.py
- hotfix/OSIS-691
- hotfix/OSIS-692
> [QA] Release

- contrib/enums/ways_find_out_about_the_course.py
- contrib/forms/training_choice.py
- contrib/views/autocomplete.py
- contrib/views/common/form_tabs/training_choice.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- templates/admission/continuing_education/details/training_choice.html
- templates/admission/forms/training_choice.html
- templatetags/enums.py
- tests/test_templatetags.py
- tests/views/curriculum/mixin.py
- tests/views/test_autocomplete.py
- tests/views/training_choice/__init__.py
- tests/views/training_choice/test_create_training_choice.py
- tests/views/training_choice/test_update_training_choice.py
> [OS-461] Add the questions about the motivation and the way to found out about the course in the training choice tab

- contrib/enums/projet.py
- contrib/views/list.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- tests/test_templatetags.py
Pull request automatique de hotfix/OS-776 vers QA
> [hotfix/OS-776 => QA] Front-office: Statuts globaux communicables aux candidats

- contrib/enums/projet.py
- contrib/views/list.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- tests/test_templatetags.py
Pull request automatique de hotfix/OS-776 vers DEV
> [hotfix/OS-776 => DEV] Front-office: Statuts globaux communicables aux candidats

- contrib/enums/projet.py
- contrib/views/common/form_tabs/documents.py
- services/proposition.py
- tests/views/test_documents.py
> [OS-681] IUFC > Add the possibility to submit the requested documents

- templates/admission/forms/training_choice.html
- templates/admission/modal/prevent_quitting_modal.html
Pull request automatique de feature/OS-1039 vers DEV
> [feature/OS-1039 => DEV] FO : Choix de formation : bug pour les doctorats demandant de préciser la commission de proximité

- contrib/views/common/form_tabs/training_choice.py
- contrib/views/mixins.py
- requirements.txt
- services/person.py
- templates/admission/continuing_education/details/training_choice.html
- templates/admission/details/specific_question.html
- templates/admission/forms/specific_question.html
- templates/admission/forms/training_choice.html
- tests/views/training_choice/__init__.py
- tests/views/training_choice/test_create_training_choice.py
- tests/views/training_choice/test_read_training_choice.py
- tests/views/training_choice/test_update_training_choice.py
> [feature/OS-1072 => DEV] Retours de tests juin FO IUFC

- services/proposition.py
- templatetags/admission.py
Pull request automatique de feature/OS-544 vers DEV
> [feature/OS-544 => DEV] Retour de tests Admission Doctorat

- constants.py
- contrib/forms/project.py
- contrib/views/common/form_tabs/confirm_submit.py
- contrib/views/doctorate/form_tabs/project.py
- contrib/views/redirect.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- requirements.txt
- services/proposition.py
- templates/admission/doctorate/forms/project.html
- templates/admission/doctorate/includes/request_signature_modal.html
- templates/admission/includes/admission_list_item.html
- templates/admission_dashboard.html
- tests/views/curriculum/mixin.py
- tests/views/curriculum/test_global.py
- tests/views/test_accounting.py
- tests/views/test_confirm_submit.py
- tests/views/test_coordonnees.py
- tests/views/test_cotutelle.py
- tests/views/test_documents.py
- tests/views/test_languages.py
- tests/views/test_list.py
- tests/views/test_pdf_recap.py
- tests/views/test_project.py
- tests/views/test_specific_question.py
- tests/views/test_supervision.py
- tests/views/training_choice/__init__.py
- tests/views/training_choice/test_read_training_choice.py
- tests/views/training_choice/test_update_training_choice.py
> [feature/OS-1130 => DEV] Admission Doctorats : éléments à corriger/finaliser/tester/vérifier après merge de tous les tickets _En test_

- contrib/views/lang.py
- templates/admission/admission_layout.html
> [hotfix/OS-1314 => QA] Front-office : A l_écran de la liste des demandes, passer l_interface en anglais lance une erreur 

- contrib/views/doctorate/form_tabs/supervision.py
- services/proposition.py
- static/admission/admission.css
- templates/admission/doctorate/forms/supervision.html
- templates/admission/doctorate/includes/request_signature_modal.html
- tests/views/test_supervision.py
Pull request automatique de feature/OS-491 vers DEV
> [feature/OS-491 => DEV] Envoi des signatures : les onglets Données personnelles et Parcours antérieur doivent être complets

- contrib/enums/training_choice.py
Approved here : https://github.com/uclouvain/osis-portal-admission/pull/690
Pull request automatique de hotfix/OS-1377 vers QA
> [hotfix/OS-1377 => QA] Front-office: Choix de formation & Conditions d_accès > Inclusion des formations FIE càd correspondant aux types 2M4 et 2M5

- contrib/enums/training_choice.py
Pull request automatique de hotfix/OS-1377 vers DEV
> [hotfix/OS-1377 => DEV] Front-office: Choix de formation & Conditions d_accès > Inclusion des formations FIE càd correspondant aux types 2M4 et 2M5

- contrib/views/common/form_tabs/specific_questions.py
- contrib/views/common/form_tabs/training_choice.py
- contrib/views/doctorate/form_tabs/project.py
- contrib/views/doctorate/form_tabs/supervision.py
- contrib/views/doctorate/supervision.py
- requirements.txt
- services/continuing_education.py
- services/proposition.py
- services/reference.py
- templatetags/admission.py
- tests/views/curriculum/mixin.py
- tests/views/curriculum/test_global.py
- tests/views/test_accounting.py
- tests/views/test_confirm_submit.py
- tests/views/test_documents.py
- tests/views/test_project.py
- tests/views/test_specific_question.py
- tests/views/test_supervision.py
- tests/views/training_choice/__init__.py
- tests/views/training_choice/test_create_training_choice.py
- tests/views/training_choice/test_update_training_choice.py
Pull request automatique de feature/OS-1435 vers DEV
> [WIP] [feature/OS-1435 => DEV] Remplacer la génération de schema par drf-spectacular (admission)

- contrib/enums/projet.py
- contrib/forms/supervision.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- templatetags/admission.py
Pull request automatique de hotfix/OS-1479 vers DEV
> [hotfix/OS-1479 => DEV] Admission doctorat : bug sur recherche de personnes 

- contrib/enums/projet.py
- contrib/forms/supervision.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- templatetags/admission.py
Pull request automatique pour la release de qa
> Release dev => qa

- services/proposition.py
- tests/views/test_supervision.py
Pull request automatique de hotfix/OS-1496 vers QA
> [hotfix/OS-1496 => QA] Admission > Doctorat : problème lors de l_édition d_un membre externe

- contrib/forms/project.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- templates/admission/doctorate/details/project.html
- templates/admission/doctorate/forms/project.html
Pull request automatique de hotfix/OS-1506 vers QA
> [hotfix/OS-1506 => QA] Doctorat Admission : onglet Recherche - Modification intitulés de documents

- templates/admission/doctorate/course_enrollment.html
- templates/admission/doctorate/forms/external_approval.html
- templates/admission/doctorate/forms/supervision.html
- templates/admission/forms/curriculum_educational_experience.html
Pull request automatique de hotfix/OS-1507 vers DEV
> [hotfix/OS-1507 => DEV] Doctorat signatures : bug sur ajout d_un membre externe

- requirements.txt
Pull request automatique de hotfix/OS-1547 vers DEV
> [hotfix/OS-1547 => DEV] Admission doctorat : bug avec un titre de projet > 255 caractères

- contrib/views/common/pdf_recap.py
- templatetags/admission.py
Pull request automatique de hotfix/OS-1552 vers QA
> [hotfix/OS-1552 => QA] Admission > Doctorat : le pdf du projet de recherche doctoral n_est pas affiché en visualisation 

- contrib/views/common/pdf_recap.py
- templatetags/admission.py
Pull request automatique de hotfix/OS-1552 vers DEV
> [hotfix/OS-1552 => DEV] Admission > Doctorat : le pdf du projet de recherche doctoral n_est pas affiché en visualisation 

- contrib/views/common/form_tabs/documents.py
- contrib/views/redirect.py
- tests/views/test_documents.py
Approved here : https://github.com/uclouvain/osis-portal-admission/pull/847
> [OS-1572] Documents > redirect the user if the candidate cannot submit the documents

- contrib/forms/__init__.py
- locale/en/LC_MESSAGES/django.po
- locale/fr_BE/LC_MESSAGES/django.po
- static/admission/initialize_phone_inputs.js
- static/admission/phone_input.css
- templates/admission/forms/coordonnees.html
Approved here : https://github.com/uclouvain/osis-portal-admission/pull/860
> [OS-1582] Coordinates > phone number : manage several masks by country

- contrib/forms/supervision.py
- contrib/views/autocomplete.py
- requirements.txt
- static/admission/admission.css
- tests/views/test_autocomplete.py
> [OS-1606] Supervision > display the email in the promoter autocomplete
